[tool.poetry]
name = "trovi"
version = "0.0.1"
description = "A collection of shared artifacts"
authors = ["Chameleon Cloud <contact@chameleoncloud.org>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1"
djangorestframework = "^3.14.0"
mysqlclient = "^2.1.1"
jsonschema = "^4.16.0"
jsonpatch = "^1.32"
cmarkgfm = "^2022.10.27"
keystoneauth1 = "^5.0.0"
python-jose = "^3.3.0"
python-keycloak-client = "^0.2.3"
drf-extensions = "^0.7.1"
PyJWT = "^2.5.0"
drf-spectacular = "^0.24.2"
giturlparse = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
flake8 = "^5.0.4"
Faker = "^15.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
