version: "3.5"

services:
  trovi:
    container_name: trovi_web_test
    image: trovi-dev:latest
    env_file:
      - .env
    environment: # Use sqlite3 for testing
      DB_ENGINE: "django.db.backends.sqlite3"
    volumes:
      - .:/project
      - media:/media
      - static:/static
    ports:
      - "127.0.0.1:8890:${TROVI_PORT}"
    entrypoint: ["python3", "manage.py"]

volumes:
  media:
  static:
