version: "3.5"

services:
  trovi:
    container_name: trovi_web_test
    image: ${DOCKER_DEV_IMAGE_LATEST}
    env_file:
      - .env
    volumes:
      - .:/project
      - media:/media
      - static:/static
    ports:
      - "127.0.0.1:8890:${TROVI_PORT}"
    entrypoint: ["python3", "manage.py"]
    depends_on:
      - db

  db:
    container_name: trovi_db_test
    image: mariadb:${DB_IMG_TAG}
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33306:${DB_PORT}
    volumes:
      - db_vol:/docker-entrypoint-initdb.d

volumes:
  media:
  static:
  db_vol:
