# Generated by Django 3.2.9 on 2021-11-24 18:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                db_index=True,
                default="private",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="artifactevent",
            name="event_type",
            field=models.CharField(
                choices=[("launch", "Launch"), ("cite", "Cite"), ("fork", "Fork")],
                db_index=True,
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="artifacttag",
            name="tag",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name="artifactproject",
            index=models.Index(
                django.db.models.functions.text.Upper("urn"), name="urn__iexact"
            ),
        ),
        migrations.AddIndex(
            model_name="artifacttag",
            index=models.Index(
                django.db.models.functions.text.Upper("tag"), name="tag__iexact"
            ),
        ),
    ]
