# Generated by Django 4.0.2 on 2022-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0006_add_artifact_sorting_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="access_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
