# Generated by Django 4.0.3 on 2022-03-30 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import trovi.fields


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0008_remove_auto_now_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactVersionMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=11,
                    ),
                ),
                ("message", models.CharField(max_length=140)),
                (
                    "message_ratio",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("chameleon", "Chameleon"), ("zenodo", "Zenodo")],
                        editable=False,
                        max_length=9,
                    ),
                ),
                ("source_urn", trovi.fields.URNField(editable=False, max_length=254)),
                ("destination_urn", trovi.fields.URNField(max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "artifact_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migrations",
                        to="trovi.artifactversion",
                    ),
                ),
            ],
        ),
    ]
