# Generated by Django 4.1 on 2022-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0009_create_artifactversionmigration_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("launch", "Launch"),
                    ("cite", "Cite"),
                    ("fork", "Fork"),
                    ("cell_execution", "Cell Execution"),
                ],
                db_index=True,
                max_length=14,
            ),
        ),
    ]
