# Generated by Django 4.1.4 on 2023-03-13 22:09

import django.db.models.deletion
from django.db import migrations, models

import trovi.fields


def create_admins(apps, _):
    artifact_model = apps.get_model("trovi", "Artifact")

    for artifact in artifact_model.objects.filter(roles=None):
        artifact.roles.create(
            user=artifact.owner_urn,
            assigned_by=artifact.owner_urn,
            role="administrator",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0010_add_cell_execution_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", trovi.fields.URNField(max_length=254)),
                ("assigned_by", trovi.fields.URNField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrator", "Administrator"),
                            ("collaborator", "Collaborator"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="trovi.artifact",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="artifactrole",
            constraint=models.UniqueConstraint(
                fields=("artifact", "user", "role"),
                name="artifact_role_unique_constraint",
            ),
        ),
        migrations.RunPython(create_admins),
    ]
