# Generated by Django 4.1.4 on 2023-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trovi", "0011_artifact_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="short_description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="title",
            field=models.CharField(max_length=140),
        ),
    ]
