# Generated by Django 4.2.17 on 2025-10-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trovi', '0013_artifactversionsetup_and_more'),
    ]

    operations = [
        migrations.RenameModel('ArtifactLink', 'ArtifactVersionLink'),
    ]
