# Generated by Django 4.2.17 on 2025-10-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trovi", "0015_alter_artifact_repro_access_hours_artifactlink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactlink",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="artifactlink",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="artifactlink",
            unique_together={("source_artifact", "linked_artifact")},
        ),
    ]
