# Generated by Django 4.2.17 on 2026-09-24 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trovi", "0020_artifactevent_artifact_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2048,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="trovi.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArtifactPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True, max_length=1000, null=True)),
                ("venue", models.CharField(blank=True, max_length=300, null=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="trovi.artifact",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
