# Generated by Django 4.2.17 on 2026-09-30 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trovi.fields


class Migration(migrations.Migration):

    dependencies = [
        ("trovi", "0021_artifactvideo_artifactpublication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", trovi.fields.URNField(max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("description", models.TextField(max_length=5000)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=8,
                    ),
                ),
                (
                    "reviewer",
                    trovi.fields.URNField(blank=True, max_length=254, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_comment", models.TextField(blank=True, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="trovi.artifact",
                    ),
                ),
                (
                    "artifact_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="trovi.artifactversion",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="trovi.artifactcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
