# Generated by Django 4.2.17 on 2026-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trovi", "0022_artifactcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactcomment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
